export interface GameMeta {
  slug: string;
  title: string;
  descriptionKey: string;
  genre: string[];
  players: '1' | '1-2' | '1-8';
  isMultiplayer: boolean;
  isLive: boolean;
  isFeatured: boolean;
  isPremium: boolean;
  thumbnail: string;
  tags: string[];
  releaseDate: string;
}

export const GAMES_REGISTRY: GameMeta[] = [
  {
    slug: 'void',
    title: 'VOID',
    descriptionKey: 'Games.void.description',
    genre: ['Horror', 'Arcade', 'Endless Runner'],
    players: '1',
    isMultiplayer: false,
    isLive: true,
    isFeatured: true,
    isPremium: false,
    thumbnail: '/og/games/void.jpg',
    tags: ['3d', 'horror', 'webgl', 'threejs', 'endless'],
    releaseDate: '2026-04-01',
  },
    // ─── Live Games ──────────────────────────────────────────────────────────
    {
      slug: 'snake',
      title: 'Snake',
      descriptionKey: 'Games.snake.description',
      genre: ['Arcade', 'Classic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/snake.svg',
      tags: ['canvas', 'arcade', 'classic', 'highscore'],
      releaseDate: '2026-05-01',
    },
    {
      slug: 'tile2048',
      title: '2048',
      descriptionKey: 'Games.tile2048.description',
      genre: ['Puzzle', 'Strategy'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/tile2048.svg',
      tags: ['puzzle', 'tiles', 'strategy', 'merge'],
      releaseDate: '2026-05-01',
    },
    {
      slug: 'heist',
      title: 'Heist Planner',
      descriptionKey: 'Games.heist.description',
      genre: ['Puzzle', 'Strategy', 'Crime'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/heist.svg',
      tags: ['puzzle', 'strategy', 'crime', 'planning'],
      releaseDate: '2026-05-15',
    },
    // ─── Coming Soon ─────────────────────────────────────────────────────────
    {
      slug: 'getaway',
      title: 'Getaway Driver',
      descriptionKey: 'Games.getaway.description',
      genre: ['Arcade', 'Crime'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/getaway.svg',
      tags: ['driving', 'arcade', 'crime', 'launch-wave-3', 'mobile'],
      releaseDate: '2026-07-01',
    },
    {
      slug: 'detective',
      title: 'Detective Mind',
      descriptionKey: 'Games.detective.description',
      genre: ['Puzzle', 'Mystery'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/detective.svg',
      tags: ['mystery', 'puzzle', 'deduction', 'launch-wave-3', 'logic'],
      releaseDate: '2026-07-15',
    },
    {
      slug: 'wordwire',
      title: 'Word Wire',
      descriptionKey: 'Games.wordwire.description',
      genre: ['Word', 'Puzzle'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/wordwire.svg',
      tags: ['word', 'puzzle', 'vocabulary', 'launch-wave-3', 'brain'],
      releaseDate: '2026-08-01',
    },
    {
      slug: 'codegolf',
      title: 'Code Golf',
      descriptionKey: 'Games.codegolf.description',
      genre: ['Programming', 'Puzzle'],
      players: '1',
      isMultiplayer: false,
      isLive: false,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/codegolf.jpg',
      tags: ['programming', 'puzzle', 'developer'],
      releaseDate: '2026-08-15',
    },
    {
      slug: 'stackblitz',
      title: 'Stack Blitz',
      descriptionKey: 'Games.stackblitz.description',
      genre: ['Arcade', 'Reflex'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/stackblitz.svg',
      tags: ['arcade', 'reflex', 'stacking', 'launch-wave-3', 'timing'],
      releaseDate: '2026-09-01',
    },
    {
      slug: 'hackrun',
      title: 'Hack Run',
      descriptionKey: 'Games.hackrun.description',
      genre: ['Hacking', 'Puzzle'],
      players: '1',
      isMultiplayer: false,
      isLive: false,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/hackrun.jpg',
      tags: ['hacking', 'terminal', 'puzzle', 'developer'],
      releaseDate: '2026-09-15',
    },
    {
      slug: 'memflip',
      title: 'Mem Flip',
      descriptionKey: 'Games.memflip.description',
      genre: ['Memory', 'Casual'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/memflip.svg',
      tags: ['memory', 'cards', 'casual', 'launch-wave-4', 'brain'],
      releaseDate: '2026-10-01',
    },
    {
      slug: 'gravityball',
      title: 'Gravity Ball',
      descriptionKey: 'Games.gravityball.description',
      genre: ['Physics', 'Arcade'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/gravityball.svg',
      tags: ['physics', 'arcade', 'ball', 'launch-wave-4', 'reflex'],
      releaseDate: '2026-10-15',
    },
    {
      slug: 'tetris',
      title: 'Tetris',
      descriptionKey: 'Games.tetris.description',
      genre: ['Puzzle', 'Arcade'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/tetris.svg',
      tags: ['blocks', 'puzzle', 'launch-wave-1', 'mobile'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'flappy-bird',
      title: 'Flappy Bird',
      descriptionKey: 'Games.flappy-bird.description',
      genre: ['Arcade', 'Reflex'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/flappy-bird.svg',
      tags: ['tap', 'reflex', 'launch-wave-1', 'mobile'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'custom-flappy',
      title: 'Custom Flappy',
      descriptionKey: 'Games.flappy-bird.description',
      genre: ['Arcade', 'Creator'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/custom-flappy.svg',
      tags: ['tap', 'custom', 'creator', 'login-required'],
      releaseDate: '2026-03-18',
    },
    {
      slug: 'mouse-maze',
      title: 'Mouse Maze',
      descriptionKey: 'Games.memflip.description',
      genre: ['Reflex', 'Arcade'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/mouse-maze.svg',
      tags: ['mouse', 'reflex', 'neon', 'login-required'],
      releaseDate: '2026-03-18',
    },
    {
      slug: 'memory-match',
      title: 'Memory Match',
      descriptionKey: 'Games.memory-match.description',
      genre: ['Puzzle', 'Memory'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/memory-match.svg',
      tags: ['cards', 'memory', 'launch-wave-1', 'casual'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'minesweeper',
      title: 'Minesweeper',
      descriptionKey: 'Games.minesweeper.description',
      genre: ['Puzzle', 'Strategy'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/minesweeper.svg',
      tags: ['logic', 'classic', 'launch-wave-1', 'strategy'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'word-scramble',
      title: 'Word Scramble',
      descriptionKey: 'Games.word-scramble.description',
      genre: ['Word', 'Puzzle'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/word-scramble.svg',
      tags: ['word', 'vocabulary', 'launch-wave-1', 'brain'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'typing-race',
      title: 'Typing Race',
      descriptionKey: 'Games.typing-race.description',
      genre: ['Typing', 'Skill'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/typing-race.svg',
      tags: ['typing', 'wpm', 'launch-wave-1', 'speed'],
      releaseDate: '2026-06-01',
    },
    {
      slug: 'sudoku',
      title: 'Sudoku',
      descriptionKey: 'Games.sudoku.description',
      genre: ['Puzzle', 'Logic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/sudoku.svg',
      tags: ['logic', 'numbers', 'launch-wave-2', 'brain'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'chess',
      title: 'Chess',
      descriptionKey: 'Games.chess.description',
      genre: ['Strategy', 'Board'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: true,
      isPremium: false,
      thumbnail: '/og/games/chess.svg',
      tags: ['board', 'strategy', 'launch-wave-2', 'cpu'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'connect-four',
      title: 'Connect Four',
      descriptionKey: 'Games.connect-four.description',
      genre: ['Strategy', 'Classic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/connect-four.svg',
      tags: ['classic', 'grid', 'launch-wave-2', 'cpu'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'breakout',
      title: 'Breakout',
      descriptionKey: 'Games.breakout.description',
      genre: ['Arcade', 'Classic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/breakout.svg',
      tags: ['arcade', 'bricks', 'launch-wave-2', 'reflex'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'pong',
      title: 'Pong',
      descriptionKey: 'Games.pong.description',
      genre: ['Arcade', 'Classic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/pong.svg',
      tags: ['arcade', 'retro', 'launch-wave-2', 'cpu'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'fifteen-puzzle',
      title: '15 Puzzle',
      descriptionKey: 'Games.fifteen-puzzle.description',
      genre: ['Puzzle', 'Logic'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/fifteen-puzzle.svg',
      tags: ['tiles', 'logic', 'launch-wave-2', 'brain'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'hangman',
      title: 'Hangman',
      descriptionKey: 'Games.hangman.description',
      genre: ['Word', 'Casual'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/hangman.svg',
      tags: ['word', 'letters', 'launch-wave-2', 'vocabulary'],
      releaseDate: '2026-06-08',
    },
    {
      slug: 'reaction-tap',
      title: 'Reaction Tap',
      descriptionKey: 'Games.reaction-tap.description',
      genre: ['Skill', 'Reflex'],
      players: '1',
      isMultiplayer: false,
      isLive: true,
      isFeatured: false,
      isPremium: false,
      thumbnail: '/og/games/reaction-tap.svg',
      tags: ['reflex', 'speed', 'launch-wave-2', 'mobile'],
      releaseDate: '2026-06-08',
    },
];

export const getAllGames = (): GameMeta[] =>
  GAMES_REGISTRY.filter((g) => g.isLive);

export const getFeaturedGames = (): GameMeta[] =>
  GAMES_REGISTRY.filter((g) => g.isLive && g.isFeatured);

export const getGameBySlug = (slug: string): GameMeta | undefined =>
  GAMES_REGISTRY.find((g) => g.slug === slug);

  export const getUpcomingGames = (): GameMeta[] =>
    GAMES_REGISTRY.filter((g) => !g.isLive);
